name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm Install
        
      
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        env:
          CI: true # Set CI environment variable for better test output in CI

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()  # Ensure the report is uploaded even if tests fail
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30 # Keep the report for 7 days